# https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/springsql_db
    username: junjunguo
    password: junjunguo
    driver-class-name: org.postgresql.Driver
    platform: postgresql
  # JPA (JpaBaseConfiguration, HibernateJpaAutoConfiguration)
  data:
    jpa:
      repositories:
        enabled: true # Whether to enable JPA repositories.
  jpa:
    show-sql: true
    generate-ddl: true # Whether to initialize the schema on startup.
    hibernate:
      ddl-auto: create-drop
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        order_updates: true
        generate_statistics: true
        temp:
          use_jdbc_metadata_defaults: false
  # FLYWAY (FlywayProperties)
  flyway:
    enabled: false
    baseline-on-migrate: false

# CORE PROPERTIES
debug: false # Enable debug logs.
trace: false # Enable trace logs.

logging:
  file: /Users/Junjun/Repository/logs/logs.log
  pattern:
    dateformat: yyyy.MM.dd HH:mm:ss.SSS
  level:
    root: error
    org:
      springframework:
        security:
          oauth2: debug
        web: error
      hibernate: debug

